### ISSUE TITLE
Failed on `pixi add mini-racer --pypi` , but pip install success

### ISSUE THREAD

**Issue by veinkr** [prefix-dev/rattler-build#1008]
Currently I failed to add this library, but can install it with pip

My question is that why pixi need to build this library, but pip can just install the whl, it seems different behaviors.

It seems it stuck on
 ```
 Preparing distributi [00:00:15] [────────────────────]    0/1    building mini-racer==0.12.4 (+1) 
```

**Comment by veinkr** [comment]
```
fatal: fetch-pack: invalid index-pack output
      1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://
      chromium.googlesource.com/v8/v8.git" "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/
      e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/_gclient_v8_mxn7exo7"' in /root/.cache/rattler/cache/uv-cache/built-
      wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace failed; will retry after a short
      nap...
      
      ________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/
      v8/v8.git /root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/_gclient_v8_mxn7exo7' in '/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/
      e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace' attempt 2 / 2
      Cloning into '/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/_gclient_v8_mxn7exo7'...
      error: RPC failed; curl 55 Failed sending data to the peer
      1>WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://
      chromium.googlesource.com/v8/v8.git" "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/
      e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/_gclient_v8_mxn7exo7"' in /root/.cache/rattler/cache/uv-cache/built-
      wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace failed; will retry after a short
      nap...
      --- stderr:
      DEBUG:helpers.v8_build:Using already cloned depot tools
      DEBUG:helpers.v8_build:Calling: '/root/.cache/rattler/cache/uv-cache/environments-v0/.tmpBs0wnO/bin/python /root/.cache/rattler/
      cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/depot_tools/
      gclient.py sync --revision v8@branch-heads/12.6' from working directory /root/.cache/rattler/cache/uv-cache/built-wheels-v3/
      pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace
      /root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/
      v8_workspace/depot_tools/gclient.py:3331: SyntaxWarning: invalid escape sequence '\s'
        dot_git_pattern = re.compile('^(\s*)url(\s*)=.*\.git$')
      
      v8 (ERROR)
      ----------------------------------------
      [0:00:00] Started.
      [0:00:00]
      Traceback (most recent call last):
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 1344, in _Clone
          self._Run(clone_cmd,
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 1691, in _Run
          gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_utils.py", line 714, in CheckCallAndFilter
          raise subprocess2.CalledProcessError(rv, args, kwargs.get('cwd', None),
      subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://
      chromium.googlesource.com/v8/v8.git /root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/
      e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/_gclient_v8_mxn7exo7' returned non-zero exit status -13 in /
      root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/
      v8_workspace
      [1:17:07] _____ Conflicting directory found in /root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/
      e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/v8. Moving to /root/.cache/rattler/cache/uv-cache/built-wheels-v3/
      pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/_bad_scm/v878n93h3h.
      ----------------------------------------
      
      
      Warnings:
      Conflicting directory /root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/
      mini_racer-0.12.4.tar.gz/v8_workspace/v8 moved to /root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/
      e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/_bad_scm/v878n93h3h.
      Traceback (most recent call last):
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 787, in update
          self.current_revision = self._Clone(revision, url, options)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 1344, in _Clone
          self._Run(clone_cmd,
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 1691, in _Run
          gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_utils.py", line 714, in CheckCallAndFilter
          raise subprocess2.CalledProcessError(rv, args, kwargs.get('cwd', None),
      subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://
      chromium.googlesource.com/v8/v8.git /root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/
      e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/_gclient_v8_mxn7exo7' returned non-zero exit status -13 in /
      root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/
      v8_workspace
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/root/luanqibazao/.pixi/envs/default/lib/python3.12/shutil.py", line 847, in move
          os.rename(src, real_dst)
      FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-
      racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/v8' -> '/root/.cache/rattler/cache/uv-cache/built-
      wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/_bad_scm/v878n93h3h/v8'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/metrics.py", line 290, in print_notice_and_exit
          yield
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient.py", line 4638, in <module>
          sys.exit(main(sys.argv[1:]))
                   ^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient.py", line 4624, in main
          return dispatcher.execute(OptionParser(), argv)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/subcommand.py", line 254, in execute
          return command(parser, args[1:])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient.py", line 3977, in CMDsync
          ret = client.RunOnDeps('update', args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient.py", line 2436, in RunOnDeps
          work_queue.flush(revision_overrides,
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_utils.py", line 1026, in flush
          reraise(e[0], e[1], e[2])
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_utils.py", line 53, in reraise
          raise value
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_utils.py", line 1105, in run
          self.item.run(*self.args, **self.kwargs)
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient.py", line 1251, in run
          self._got_revision = self._used_scm.RunCommand(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 135, in RunCommand
          return getattr(self, command)(options, args, file_list)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 662, in wrapper
          return_val = f(*args)
                       ^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 790, in update
          self._DeleteOrMove(options.force)
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/v8_workspace/depot_tools/gclient_scm.py", line 207, in _DeleteOrMove
          shutil.move(self.checkout_path, dest_path)
        File "/root/luanqibazao/.pixi/envs/default/lib/python3.12/shutil.py", line 867, in move
          copy_function(src, real_dst)
        File "/root/luanqibazao/.pixi/envs/default/lib/python3.12/shutil.py", line 475, in copy2
          copyfile(src, dst, follow_symlinks=follow_symlinks)
        File "/root/luanqibazao/.pixi/envs/default/lib/python3.12/shutil.py", line 260, in copyfile
          with open(src, 'rb') as fsrc:
               ^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-
      racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/v8_workspace/v8'
      Traceback (most recent call last):
        File "<string>", line 11, in <module>
        File "/root/.cache/rattler/cache/uv-cache/environments-v0/.tmpBs0wnO/lib/python3.12/site-packages/hatchling/build.py", line
      58, in build_wheel
          return os.path.basename(next(builder.build(directory=wheel_directory, versions=['standard'])))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/environments-v0/.tmpBs0wnO/lib/python3.12/site-packages/hatchling/builders/plugin/
      interface.py", line 147, in build
          build_hook.initialize(version, build_data)
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/hatch_build.py", line 24, in initialize
          artifacts = build_v8(out_path="src/py_mini_racer")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/helpers/v8_build.py", line 413, in build_v8
          ensure_v8_src(revision)
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/helpers/v8_build.py", line 233, in ensure_v8_src
          run(
        File "/root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-
      0.12.4.tar.gz/helpers/v8_build.py", line 163, in run
          return check_call(args, env=env, cwd=cwd)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/root/luanqibazao/.pixi/envs/default/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '('/root/.cache/rattler/cache/uv-cache/environments-v0/.tmpBs0wnO/bin/python', '/
      root/.cache/rattler/cache/uv-cache/built-wheels-v3/pypi/mini-racer/0.12.4/e7EGpoOAwpoDxVQuBb4w3/mini_racer-0.12.4.tar.gz/
      v8_workspace/depot_tools/gclient.py', 'sync', '--revision', 'v8@branch-heads/12.6')' returned non-zero exit status 1.
      ---
```
