### ISSUE TITLE
trying to convert a recipe to rattler-build fails with: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp1m0a0rby/openglider-feedstock/recipe/meta.yaml'

### ISSUE THREAD

**Issue by looooo** [prefix-dev/rattler-build#1291]
As the title says I am running into an issue trying to rerender a recipe which was updated to rattler-build by replacing meta.yaml with recipe.yaml by using conda-recipe-manager. 

REF: https://github.com/conda-forge/openglider-feedstock/pull/10

Error:
```
Traceback (most recent call last):
  File "/opt/conda/envs/cf-feedstock-ops/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/cli.py", line 767, in main
    args.subcommand_func(args)
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/cli.py", line 610, in __call__
    self._call(args, args.temporary_directory)
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/cli.py", line 613, in _call
    configure_feedstock.main(
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2880, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 1900, in render_azure
    return _render_ci_provider(
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/cf-feedstock-ops/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 1025, in _render_ci_provider
    with open(
         ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp1m0a0rby/openglider-feedstock/recipe/meta.yaml
```

**Comment by looooo** [comment]
I tried this instruction:
```pixi global install conda-recipe-manager conda-smithy # if you don't have it already
conda-recipe-manager convert ./recipe/meta.yaml > ./recipe/recipe.yaml
 
# when things work, remove the meta.yaml file
rm ./recipe/meta.yaml
# rerender with conda-smithy
conda-smithy rerender
# and push a PR to your feedstock!
```

from https://prefix.dev/blog/rattler_build_on_conda_forge

**Comment by wolfv** [comment]
Did you change the build tool value in conda-forge.yml

**Comment by looooo** [comment]
thanks, adding `conda_build_tool: rattler-build` in the `conda-forge.yaml`did the trick.
