### ISSUE TITLE
Support injecting the `environ` variable in recipes

### ISSUE THREAD

**Issue by dhirschfeld** [prefix-dev/rattler-build#138]
...which `boa` works for.

```
❯ rattler-build build --recipe-file ./build/conda/recipe.yaml
 INFO rattler_build: Starting the build process
 INFO rattler_build: No target platform specified, using current platform
Found variants:
╭─────────────────┬──────────╮
│ Variant         ┆ Version  │
╞═════════════════╪══════════╡
│ target_platform ┆ linux-64 │
╰─────────────────┴──────────╯

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UndefinedError, name: "<string>", line: 1 }', src/render/recipe.rs:123:74
stack backtrace:
   0:     0x55f878b5213a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55f878b5213a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f878b5213a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x55f878b5213a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55f878b7d8de - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x55f878b4d795 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x55f878b51f05 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x55f878b51f05 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x55f878b536bf - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x55f878b533fb - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x55f878b53c68 - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:692:13
  11:     0x55f878b53b69 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  12:     0x55f878b525a6 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  13:     0x55f878b53872 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  14:     0x55f87818ccf3 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  15:     0x55f87818d1a3 - core::result::unwrap_failed::hdff5465d74574b44
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
  16:     0x55f8782f4863 - rattler_build::render::recipe::render_recipe::h1091a334c82e2ed9
  17:     0x55f87836e6a3 - rattler_build::run_build_from_args::{{closure}}::hcfc39f2258319605
  18:     0x55f8783712b6 - rattler_build::main::{{closure}}::h51a545dcc6054cd2
  19:     0x55f878351386 - tokio::runtime::context::BlockingRegionGuard::block_on::h98038fbba076f2c9
  20:     0x55f8782124fb - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::ha18e7cb6fb9e086f
  21:     0x55f8782beed0 - tokio::runtime::runtime::Runtime::block_on::hf87ebd0dace1c556
  22:     0x55f87831f6df - rattler_build::main::h9434a6185ad6cc85
  23:     0x55f878218453 - std::sys_common::backtrace::__rust_begin_short_backtrace::h61a6a709095f2fb1
  24:     0x55f8781d3e3d - std::rt::lang_start::{{closure}}::h744d5772ab20b6e7
  25:     0x55f878b4663c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hd6efcd3bec896f2c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287:13
  26:     0x55f878b4663c - std::panicking::try::do_call::hce04e543bb1f4cbb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  27:     0x55f878b4663c - std::panicking::try::h3342dd4e1f680968
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  28:     0x55f878b4663c - std::panic::catch_unwind::h148ce1e59ac0cee7
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  29:     0x55f878b4663c - std::rt::lang_start_internal::{{closure}}::h25f9dda2057a67fe
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:48
  30:     0x55f878b4663c - std::panicking::try::do_call::h7caaaeaf9401650b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487:40
  31:     0x55f878b4663c - std::panicking::try::he7d15285746cbbc2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451:19
  32:     0x55f878b4663c - std::panic::catch_unwind::h89fb4f50c0301fe0
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140:14
  33:     0x55f878b4663c - std::rt::lang_start_internal::h078acd489417d3c1
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148:20
  34:     0x55f87831f7c5 - main
  35:     0x7f0c17b4bd90 - <unknown>
  36:     0x7f0c17b4be40 - __libc_start_main
  37:     0x55f87818d335 - <unknown>
```
```yaml
context:
  name: dwgm-forecast
  version: "{{ environ['SETUPTOOLS_SCM_PRETEND_VERSION'] }}"

package:
  name: "{{ name }}"
  version: "{{ version }}"

build:
  number: 0

outputs:
  - package:
      name: "{{ name }}"
      version: "{{ version }}"

    build:
      noarch: python
      script_env:
        PIP_ROOT_USER_ACTION: "ignore"
      script: echo "test" $PREFIX/test.txt

    requirements:
      host:
        - python >=3.10
        - hatchling
        - hatch-vcs
        - pip >=22.3

      run:
        - python >=3.10
        - click
        - numpy
        - pandas
        - scikit-learn
        - scikit-learn-intelex
        - sqlalchemy
        - statsmodels

about:
  summary: 'Bug report'
```

**Comment by dhirschfeld** [comment]
Perhaps `environ` isn't supported?

**Comment by ruben-arts** [comment]
> Perhaps `environ` isn't supported?

Yes that is indeed the issue here. The outputs part is also not implemented yet. It needs requirements in the root of the file.

**Comment by dhirschfeld** [comment]
Outputs is an easy fix. I'm not sure how else I could support injecting the correct version from CI... other than codegen 😬

**Comment by dhirschfeld** [comment]
> Yes that is indeed the issue here.

I guess the TODO here could be a more informative error message, if possible.

**Comment by dhirschfeld** [comment]
I changed this to a feature request issue.

In case it's useful, the same was added to `boa` in https://github.com/mamba-org/boa/pull/299

**Comment by wolfv** [comment]
I am not totally against this idea, but we need to make sure to store these environment variables that were used somewhere, so that we can reproduce the build later on.
