### ISSUE TITLE
Relative paths with git url

### ISSUE THREAD

**Issue by wolfv** [prefix-dev/rattler-build#140]
It was reported that relative paths don't seem to work properly with the git source yet.

**Comment by wolfv** [comment]
cc @ruben-arts

**Comment by mariusvniekerk** [comment]
recipe.yaml
```
source:
  git_url: "../"
```

error

```
 INFO rattler_build::source: Fetching source from GIT: "../"
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/source.rs:175:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: rattler_build::source::git_src
   4: rattler_build::source::fetch_sources::{{closure}}
   5: rattler_build::build::run_build::{{closure}}
   6: rattler_build::run_build_from_args::{{closure}}
   7: rattler_build::main::{{closure}}
   8: tokio::runtime::park::CachedParkThread::block_on
   9: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
  10: tokio::runtime::runtime::Runtime::block_on
  11: rattler_build::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
