### ISSUE TITLE
Missing info/files

### ISSUE THREAD

**Issue by beenje** [prefix-dev/rattler-build#335]
Trying to switch from conda-build to rattler-build. It's amazing fast :-)

Today, we found an issue when trying to upload the package to our internal Quetz server:

```
INFO:  - "POST /api/channels/maxiv-kits-dev/upload/tangods-highleveldevices-3.3.4.dev4%2Bged992bf-pyh4616a5c_0.tar.bz2?force=False&sha256=8ce117cc8083d91b508b87f24b6301f832eb3dbdcbf216b34e7ecd46501f9eda HTTP/1.0" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
  File "/opt/conda/lib/python3.11/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/quetz/main.py", line 1393, in post_upload
    condainfo = CondaInfo((body), filename)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/quetz/condainfo.py", line 89, in __init__
    self._parse_conda()
  File "/opt/conda/lib/python3.11/site-packages/quetz/condainfo.py", line 202, in _parse_conda
    self._load_jsons(tar)
  File "/opt/conda/lib/python3.11/site-packages/quetz/condainfo.py", line 161, in _load_jsons
    with tar.extractfile("info/files") as fp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/tarfile.py", line 2364, in extractfile
    tarinfo = self.getmember(member)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/tarfile.py", line 1985, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/files' not found"
```

Comparing the same package created by rattler-build and conda-build:

For conda-build (actually conda mambabuild):

```
tree conda-build/info
conda-build/info
├── about.json
├── files
├── git
├── hash_input.json
├── index.json
├── licenses
│   └── LICENSE.txt
├── link.json
├── paths.json
├── recipe
│   ├── conda_build_config.yaml
│   ├── meta.yaml
│   └── meta.yaml.template
└── test
    ├── run_test.bat
    ├── run_test.py
    ├── run_test.sh
    └── test_time_dependencies.json
```

For rattler-build:

```rattler-build/info
├── about.json
├── index.json
├── licenses
│   └── LICENSE.txt
├── link.json
├── paths.json
├── recipe
│   ├── recipe.yaml
│   ├── rendered_recipe.yaml
│   └── variant_config.yaml
└── test
    ├── run_test.bat
    ├── run_test.py
    ├── run_test.sh
    └── test_time_dependencies.json
```

`info/files` is missing (as well as `info/hash_input.json` and `info/git`).
My guess is that this is on purpose as information in `info/files` seems redundant with` info/paths.json`, and it doesn't prevent recent version of conda to install the package.
But that might break compatibility with other tools?

Just wanted to check before to open an issue in Quetz repo.

**Comment by beenje** [comment]
Looking at https://docs.conda.io/projects/conda/en/stable/user-guide/concepts/pkg-specs.html#info-files, this seems to be required by the specs.

**Comment by wolfv** [comment]
Ah, annoying, I didn't remember that `quetz` requires this file. The data is indeed duplicated from `paths.json`.
We should totally write the `hash_input.json` file.

Can you paste the approximate contents of `info/git`? I am not sure if we are going to write that file because there are some weird semantics surrounding git repositories & conda-build.
We would rather store the used git commit (ref) in the rendered recipe per source.

**Comment by wolfv** [comment]
I looked into fixing this but it's a bit annoying because to support this API we would also have to add `has_prefix` files and so on.

Instead, I've made the following (untested) modification to quetz: https://github.com/mamba-org/quetz/pull/671

**Comment by wolfv** [comment]
The `hash_input.json` is now written in #338

**Comment by wolfv** [comment]
I am adding a documentation label so that we don't forget to document this difference in our documentation.
