### ISSUE TITLE
`unsupported platform` when building for win-64 on Linux

### ISSUE THREAD

**Issue by MartinJepsen** [prefix-dev/rattler-build#812]
I am really enjoying rattler-build so far. I have run into a problem that I can't seem to solve.

Any help would be greatly appreciated.

When running

```bash
rattler-build build --recipe build --target-platform win-64
```

on Ubuntu WSL, I get the following:

```
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rattler-0.21.0/src/install/entry_point.rs:18:14:
unsupported platform
```

The error happens during "Resolving environments". 

### Full output

<details>
<summary>Click to expand</summary>

```
user@host:~/repo$ ./rattler-build-x86_64-unknown-linux-musl build --recipe build/ --target-platform win-64

 ╭─ Finding outputs from recipe
 │ ⚠ warning invalid url for `GitSource` `../`: relative URL without a base
 │ ⚠ warning attempting to parse as path
 │ ⚠ warning invalid url for `GitSource` `../`: relative URL without a base
 │ ⚠ warning attempting to parse as path
 │ ⚠ warning invalid url for `GitSource` `../`: relative URL without a base
 │ ⚠ warning attempting to parse as path
 │ ⚠ warning invalid url for `GitSource` `../`: relative URL without a base
 │ ⚠ warning attempting to parse as path
 │ Found 1 variants
 │ Build variant: bhbfile-0.1.1-h9490d1a_0
 │ 
 │ ╭─────────────────┬─────────╮
 │ │ Variant         ┆ Version │
 │ ╞═════════════════╪═════════╡
 │ │ target_platform ┆ win-64  │
 │ ╰─────────────────┴─────────╯
 │
 ╰─────────────────── (took 0 seconds)
 ⚠ warning invalid url for `GitSource` `../`: relative URL without a base
 ⚠ warning attempting to parse as path

 ╭─ Checking existing builds
 │
 ╰─────────────────── (took 0 seconds)

 ╭─ Running build for recipe: bhbfile-0.1.1-h9490d1a_0
 │
 │ ╭─ Fetching source code
 │ │ Fetching source from git repo: "../"
Cloning into '/home/user/repo/'...
remote: Enumerating objects: 149, done.
remote: Counting objects: 100% (149/149), done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 149 (delta 60), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (149/149), 7.13 MiB | 13.72 MiB/s, done.
Resolving deltas: 100% (60/60), done.
 │ │ Checked out revision: 'refs/tags/0.1.1' at '682abb882b6af20994818fa6da3a830cc3894587'
 │ │ Copied 55 files into isolated environment
 │ │
 │ ╰─────────────────── (took 1 second)
 │
 │ ╭─ Resolving environments
 │ │ 
 │ │ Resolving environment for:
 │ │   Platform: linux-64
 │ │   Channels: 
 │ │    - /home/user/repo/output
 │ │    - conda-forge
 │ │   Specs:
 │ │    - rust_win-64
 │ │ ✔ /home/user/repo [00:00:00] Using cache
 │ │ 
 │ │ ╭───────────────────────────────────┬──────────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package                           ┆ Version      ┆ Build              ┆ Channel     ┆ Size       │
 │ │ ╞═══════════════════════════════════╪══════════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ rust_win-64                       ┆ 1.77.2       ┆ h248e1ec_2         ┆ conda-forge ┆ 9.94 KiB   │
 │ │ │ rust-std-x86_64-pc-windows-msvc   ┆ 1.77.2       ┆ unix_0             ┆ conda-forge ┆ 24.10 MiB  │
 │ │ │ rust                              ┆ 1.77.2       ┆ h70c747d_0         ┆ conda-forge ┆ 178.11 MiB │
 │ │ │ rust-std-x86_64-unknown-linux-gnu ┆ 1.77.2       ┆ h2c6d0dc_0         ┆ conda-forge ┆ 32.26 MiB  │
 │ │ │ libzlib                           ┆ 1.2.13       ┆ hd590300_5         ┆ conda-forge ┆ 60.14 KiB  │
 │ │ │ libgcc-ng                         ┆ 13.2.0       ┆ h807b86a_5         ┆ conda-forge ┆ 752.45 KiB │
 │ │ │ _libgcc_mutex                     ┆ 0.1          ┆ conda_forge        ┆ conda-forge ┆ 2.50 KiB   │
 │ │ │ _openmp_mutex                     ┆ 4.5          ┆ 2_gnu              ┆ conda-forge ┆ 23.07 KiB  │
 │ │ │ libgomp                           ┆ 13.2.0       ┆ h807b86a_5         ┆ conda-forge ┆ 409.91 KiB │
 │ │ │ ninja                             ┆ 1.12.0       ┆ h00ab1b0_0         ┆ conda-forge ┆ 2.11 MiB   │
 │ │ │ libstdcxx-ng                      ┆ 13.2.0       ┆ h7e041cc_5         ┆ conda-forge ┆ 3.66 MiB   │
 │ │ │ clang_win-64                      ┆ 18.1.2       ┆ h8c19e41_7         ┆ conda-forge ┆ 29.36 KiB  │
 │ │ │ llvm-tools                        ┆ 18.1.2       ┆ h2448989_0         ┆ conda-forge ┆ 31.14 MiB  │
 │ │ │ lld                               ┆ 18.1.2       ┆ hd326a66_0         ┆ conda-forge ┆ 6.50 MiB   │
 │ │ │ compiler-rt_win-64                ┆ 18.1.2       ┆ h91493d7_0         ┆ conda-forge ┆ 3.79 MiB   │
 │ │ │ compiler-rt                       ┆ 18.1.2       ┆ h00ab1b0_0         ┆ conda-forge ┆ 109.19 KiB │
 │ │ │ zstd                              ┆ 1.5.5        ┆ hfc55251_0         ┆ conda-forge ┆ 532.42 KiB │
 │ │ │ libllvm18                         ┆ 18.1.2       ┆ h2448989_0         ┆ conda-forge ┆ 36.63 MiB  │
 │ │ │ compiler-rt_linux-64              ┆ 18.1.2       ┆ h00ab1b0_0         ┆ conda-forge ┆ 39.56 MiB  │
 │ │ │ clangxx                           ┆ 18.1.2       ┆ default_h127d8a8_1 ┆ conda-forge ┆ 22.47 KiB  │
 │ │ │ clang                             ┆ 18.1.2       ┆ default_h90ac42e_1 ┆ conda-forge ┆ 22.37 KiB  │
 │ │ │ clang-18                          ┆ 18.1.2       ┆ default_h127d8a8_1 ┆ conda-forge ┆ 754.73 KiB │
 │ │ │ libclang-cpp18.1                  ┆ 18.1.2       ┆ default_h127d8a8_1 ┆ conda-forge ┆ 18.38 MiB  │
 │ │ │ msvc-headers-libs                 ┆ 14.38.33130  ┆ hc0367c8_4         ┆ conda-forge ┆ 31.23 KiB  │
 │ │ │ libxml2                           ┆ 2.12.6       ┆ h232c23b_2         ┆ conda-forge ┆ 688.42 KiB │
 │ │ │ xz                                ┆ 5.2.6        ┆ h166bdaf_0         ┆ conda-forge ┆ 408.56 KiB │
 │ │ │ icu                               ┆ 73.2         ┆ h59595ed_0         ┆ conda-forge ┆ 11.53 MiB  │
 │ │ │ libiconv                          ┆ 1.17         ┆ hd590300_2         ┆ conda-forge ┆ 689.23 KiB │
 │ │ │ unzip                             ┆ 6.0          ┆ h7f98852_3         ┆ conda-forge ┆ 165.18 KiB │
 │ │ │ winsdk                            ┆ 10.0.22621.0 ┆ hd73dd49_4         ┆ conda-forge ┆ 35.98 KiB  │
 │ │ │ p7zip                             ┆ 16.02        ┆ h9c3ff4c_1001      ┆ conda-forge ┆ 2.20 MiB   │
 │ │ │ msitools                          ┆ 0.103        ┆ h0da5c8a_0         ┆ conda-forge ┆ 533.85 KiB │
 │ │ │ libuuid                           ┆ 2.38.1       ┆ h0b41bf4_0         ┆ conda-forge ┆ 32.81 KiB  │
 │ │ │ gcab                              ┆ 1.6          ┆ h6ee01cb_0         ┆ conda-forge ┆ 87.13 KiB  │
 │ │ │ gettext                           ┆ 0.22.5       ┆ h59595ed_2         ┆ conda-forge ┆ 463.92 KiB │
 │ │ │ libgettextpo-devel                ┆ 0.22.5       ┆ h59595ed_2         ┆ conda-forge ┆ 35.90 KiB  │
 │ │ │ libgettextpo                      ┆ 0.22.5       ┆ h59595ed_2         ┆ conda-forge ┆ 166.58 KiB │
 │ │ │ libasprintf-devel                 ┆ 0.22.5       ┆ h661eb56_2         ┆ conda-forge ┆ 33.42 KiB  │
 │ │ │ libasprintf                       ┆ 0.22.5       ┆ h661eb56_2         ┆ conda-forge ┆ 42.21 KiB  │
 │ │ │ gettext-tools                     ┆ 0.22.5       ┆ h59595ed_2         ┆ conda-forge ┆ 2.60 MiB   │
 │ │ │ libgsf                            ┆ 1.14.51      ┆ haef5bb9_1         ┆ conda-forge ┆ 394.80 KiB │
 │ │ │ zlib                              ┆ 1.2.13       ┆ hd590300_5         ┆ conda-forge ┆ 90.65 KiB  │
 │ │ │ pcre                              ┆ 8.45         ┆ h9c3ff4c_0         ┆ conda-forge ┆ 253.30 KiB │
 │ │ │ bzip2                             ┆ 1.0.8        ┆ hd590300_5         ┆ conda-forge ┆ 248.27 KiB │
 │ │ │ libglib                           ┆ 2.80.0       ┆ hf2295e7_5         ┆ conda-forge ┆ 3.71 MiB   │
 │ │ │ pcre2                             ┆ 10.43        ┆ hcad00b1_0         ┆ conda-forge ┆ 928.56 KiB │
 │ │ │ glib                              ┆ 2.80.0       ┆ hf2295e7_5         ┆ conda-forge ┆ 585.31 KiB │
 │ │ │ glib-tools                        ┆ 2.80.0       ┆ hde27a5a_5         ┆ conda-forge ┆ 112.47 KiB │
 │ │ │ libffi                            ┆ 3.4.2        ┆ h7f98852_5         ┆ conda-forge ┆ 56.93 KiB  │
 │ │ │ sysroot_linux-64                  ┆ 2.12         ┆ he073ed8_17        ┆ conda-forge ┆ 14.43 MiB  │
 │ │ │ kernel-headers_linux-64           ┆ 2.6.32       ┆ he073ed8_17        ┆ conda-forge ┆ 693.97 KiB │
 │ │ │ binutils_impl_linux-64            ┆ 2.40         ┆ hf600244_0         ┆ conda-forge ┆ 5.16 MiB   │
 │ │ │ ld_impl_linux-64                  ┆ 2.40         ┆ h41732ed_0         ┆ conda-forge ┆ 688.18 KiB │
 │ │ │ gcc_impl_linux-64                 ┆ 13.2.0       ┆ h338b0a0_5         ┆ conda-forge ┆ 50.85 MiB  │
 │ │ │ libsanitizer                      ┆ 13.2.0       ┆ h7e041cc_5         ┆ conda-forge ┆ 3.92 MiB   │
 │ │ │ libgcc-devel_linux-64             ┆ 13.2.0       ┆ ha9c7c90_105       ┆ conda-forge ┆ 2.46 MiB   │
 │ │ │ gxx_impl_linux-64                 ┆ 13.2.0       ┆ h338b0a0_5         ┆ conda-forge ┆ 12.95 MiB  │
 │ │ │ libstdcxx-devel_linux-64          ┆ 13.2.0       ┆ ha9c7c90_105       ┆ conda-forge ┆ 12.42 MiB  │
 │ │ │ curl                              ┆ 8.7.1        ┆ hca28451_0         ┆ conda-forge ┆ 161.00 KiB │
 │ │ │ libssh2                           ┆ 1.11.0       ┆ h0841786_0         ┆ conda-forge ┆ 264.78 KiB │
 │ │ │ libcurl                           ┆ 8.7.1        ┆ hca28451_0         ┆ conda-forge ┆ 388.96 KiB │
 │ │ │ krb5                              ┆ 1.21.2       ┆ h659d440_0         ┆ conda-forge ┆ 1.31 MiB   │
 │ │ │ keyutils                          ┆ 1.6.1        ┆ h166bdaf_0         ┆ conda-forge ┆ 115.07 KiB │
 │ │ │ libnghttp2                        ┆ 1.58.0       ┆ h47da74e_1         ┆ conda-forge ┆ 617.12 KiB │
 │ │ │ openssl                           ┆ 3.2.1        ┆ hd590300_1         ┆ conda-forge ┆ 2.73 MiB   │
 │ │ │ libev                             ┆ 4.33         ┆ hd590300_2         ┆ conda-forge ┆ 110.12 KiB │
 │ │ │ libedit                           ┆ 3.1.20191231 ┆ he28a2e2_2         ┆ conda-forge ┆ 120.97 KiB │
 │ │ │ c-ares                            ┆ 1.28.1       ┆ hd590300_0         ┆ conda-forge ┆ 164.92 KiB │
 │ │ │ ncurses                           ┆ 6.4.20240210 ┆ h59595ed_0         ┆ conda-forge ┆ 874.68 KiB │
 │ │ │ ca-certificates                   ┆ 2024.2.2     ┆ hbcca054_0         ┆ conda-forge ┆ 151.79 KiB │
 │ │ │ python                            ┆ 3.12.3       ┆ hab00c5b_0_cpython ┆ conda-forge ┆ 30.51 MiB  │
 │ │ │ readline                          ┆ 8.2          ┆ h8228510_1         ┆ conda-forge ┆ 274.86 KiB │
 │ │ │ libnsl                            ┆ 2.0.1        ┆ hd590300_0         ┆ conda-forge ┆ 32.62 KiB  │
 │ │ │ libexpat                          ┆ 2.6.2        ┆ h59595ed_0         ┆ conda-forge ┆ 72.00 KiB  │
 │ │ │ libsqlite                         ┆ 3.45.3       ┆ h2797004_0         ┆ conda-forge ┆ 839.71 KiB │
 │ │ │ libxcrypt                         ┆ 4.4.36       ┆ hd590300_1         ┆ conda-forge ┆ 98.04 KiB  │
 │ │ │ tk                                ┆ 8.6.13       ┆ noxft_h4845f30_101 ┆ conda-forge ┆ 3.17 MiB   │
 │ │ │ tzdata                            ┆ 2024a        ┆ h0c530f3_0         ┆ conda-forge ┆ 117.01 KiB │
 │ │ │ cmake                             ┆ 3.29.2       ┆ hcfe8598_0         ┆ conda-forge ┆ 18.11 MiB  │
 │ │ │ rhash                             ┆ 1.4.4        ┆ hd590300_0         ┆ conda-forge ┆ 180.80 KiB │
 │ │ │ libuv                             ┆ 1.48.0       ┆ hd590300_0         ┆ conda-forge ┆ 878.89 KiB │
 │ │ ╰───────────────────────────────────┴──────────────┴────────────────────┴─────────────┴────────────╯
 │ │ ✔ Successfully updated the environment
 │ │ 
 │ │ Resolving environment for:
 │ │   Platform: win-64
 │ │   Channels: 
 │ │    - /home/user/repo/output
 │ │    - conda-forge
 │ │   Specs:
 │ │    - python >=3.8
 │ │    - setuptools
 │ │    - pip
 │ │    - maturin
 │ │ ✔ /home/user/repo/ [00:00:00] Using cache
 │ │ 
 │ │ ╭─────────────────────────┬────────────────────┬────────────────────┬─────────────┬────────────╮
 │ │ │ Package                 ┆ Version            ┆ Build              ┆ Channel     ┆ Size       │
 │ │ ╞═════════════════════════╪════════════════════╪════════════════════╪═════════════╪════════════╡
 │ │ │ pip                     ┆ 24.0               ┆ pyhd8ed1ab_0       ┆ conda-forge ┆ 1.33 MiB   │
 │ │ │ wheel                   ┆ 0.43.0             ┆ pyhd8ed1ab_1       ┆ conda-forge ┆ 56.60 KiB  │
 │ │ │ python                  ┆ 3.12.3             ┆ h2628c8c_0_cpython ┆ conda-forge ┆ 15.43 MiB  │
 │ │ │ xz                      ┆ 5.2.6              ┆ h8d14728_0         ┆ conda-forge ┆ 212.70 KiB │
 │ │ │ libexpat                ┆ 2.6.2              ┆ h63175ca_0         ┆ conda-forge ┆ 135.96 KiB │
 │ │ │ libsqlite               ┆ 3.45.3             ┆ hcfcfb64_0         ┆ conda-forge ┆ 850.12 KiB │
 │ │ │ libzlib                 ┆ 1.2.13             ┆ hcfcfb64_5         ┆ conda-forge ┆ 54.49 KiB  │
 │ │ │ openssl                 ┆ 3.2.1              ┆ hcfcfb64_1         ┆ conda-forge ┆ 7.85 MiB   │
 │ │ │ tk                      ┆ 8.6.13             ┆ h5226925_1         ┆ conda-forge ┆ 3.34 MiB   │
 │ │ │ ucrt                    ┆ 10.0.22621.0       ┆ h57928b3_0         ┆ conda-forge ┆ 1.22 MiB   │
 │ │ │ bzip2                   ┆ 1.0.8              ┆ hcfcfb64_5         ┆ conda-forge ┆ 121.66 KiB │
 │ │ │ libffi                  ┆ 3.4.2              ┆ h8ffe710_5         ┆ conda-forge ┆ 41.08 KiB  │
 │ │ │ maturin                 ┆ 1.5.1              ┆ py312hfab6836_0    ┆ conda-forge ┆ 4.29 MiB   │
 │ │ │ python_abi              ┆ 3.12               ┆ 4_cp312            ┆ conda-forge ┆ 6.63 KiB   │
 │ │ │ m2w64-gcc-libs-core     ┆ 5.3.0              ┆ 7                  ┆ conda-forge ┆ 214.10 KiB │
 │ │ │ m2w64-gcc-libs          ┆ 5.3.0              ┆ 7                  ┆ conda-forge ┆ 519.91 KiB │
 │ │ │ msys2-conda-epoch       ┆ 20160418           ┆ 1                  ┆ conda-forge ┆ 3.15 KiB   │
 │ │ │ m2w64-libwinpthread-git ┆ 5.0.0.4634.697f757 ┆ 2                  ┆ conda-forge ┆ 31.18 KiB  │
 │ │ │ m2w64-gmp               ┆ 6.1.0              ┆ 2                  ┆ conda-forge ┆ 726.08 KiB │
 │ │ │ m2w64-gcc-libgfortran   ┆ 5.3.0              ┆ 6                  ┆ conda-forge ┆ 342.47 KiB │
 │ │ │ tomli                   ┆ 2.0.1              ┆ pyhd8ed1ab_0       ┆ conda-forge ┆ 15.57 KiB  │
 │ │ │ tzdata                  ┆ 2024a              ┆ h0c530f3_0         ┆ conda-forge ┆ 117.01 KiB │
 │ │ │ vc14_runtime            ┆ 14.38.33130        ┆ h82b7239_18        ┆ conda-forge ┆ 732.29 KiB │
 │ │ │ vs2015_runtime          ┆ 14.38.33130        ┆ hcb4865c_18        ┆ conda-forge ┆ 16.59 KiB  │
 │ │ │ setuptools              ┆ 69.5.1             ┆ pyhd8ed1ab_0       ┆ conda-forge ┆ 490.03 KiB │
 │ │ │ ca-certificates         ┆ 2024.2.2           ┆ h56e8100_0         ┆ conda-forge ┆ 152.23 KiB │
 │ │ │ vc                      ┆ 14.3               ┆ hcf57466_18        ┆ conda-forge ┆ 16.58 KiB  │
 │ │ ╰─────────────────────────┴────────────────────┴────────────────────┴─────────────┴────────────╯
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/pip-24.0-pyhd8ed1ab_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/xz-5.2.6-h8d14728_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/python-3.12.3-h2628c8c_0_cpython" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/libexpat-2.6.2-h63175ca_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/libsqlite-3.45.3-hcfcfb64_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/openssl-3.2.1-hcfcfb64_1" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/tk-8.6.13-h5226925_1" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/ucrt-10.0.22621.0-h57928b3_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/bzip2-1.0.8-hcfcfb64_5" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/maturin-1.5.1-py312hfab6836_0" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/m2w64-gcc-libs-5.3.0-7" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/m2w64-gmp-6.1.0-2" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/m2w64-gcc-libgfortran-5.3.0-6" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/vc14_runtime-14.38.33130-h82b7239_18" failed: failed to read 'index.json'
 │ │ ⚠ warning validation for "/home/user/.cache/rattler/cache/pkgs/m2w64-gcc-libs-core-5.3.0-7" failed: failed to read 'index.json'
 │ │ ⠁ downloading          [00:00:00] [────────────────────────────────────────]       0/27     
 │ │ ⠁ linking              [00:00:00] [────────────────────────────────────────]       0/27                                                               thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rattler-0.21.0/src/install/entry_point.rs:18:14:
unsupported platform
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rattler-0.21.0/src/install/driver.rs:146:13:
internal error: entered unreachable code: if a send error occurs here it means the task processor is dropped. Since this only happens when dropping this object there cannot be another call to this function. Therefor this should never happen.
 │ │
 │ ╰─────────────────── (took 39 seconds)
 │
 ╰─────────────────── (took 39 seconds)
```

</details>

### What I've checked:

* I have used both rattler-build 0.15.0 installed via micromamba and via the binary from the releases page.
* It works perfect without specifying a `--target-platform`
* I have `python=3.12.2`, `maturin=1.5.1` and `rattler-build-0.15.0` in my micromamba environment
* I have the following rustup targets installed:
    * x86_64-unknown-linux-gnu
    * x86_64-pc-windows-msvc
    * x86_64-pc-windows-gnu
    * wasm32-unknown-unknown

### Recipe

My recipe is this:

```yaml
context:
  name: bhbfile
  version: "0.1.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  git: ../
  tag: ${{ version }}


requirements:
  build:
  - ${{ compiler('rust') }}
  host:
  - python>=3.8
  - setuptools
  - pip
  - maturin
  run:
  - python>=3.8
  - polars
```

**Comment by wolfv** [comment]
This is the fix for the panic: https://github.com/mamba-org/rattler/pull/608 - will be in with the next release!

**Comment by MartinJepsen** [comment]
Holy cow. That was fast. Thanks so much!

**Comment by wolfv** [comment]
Sorry - while we have the fix, the release is only coming today :)
